-- MySQL Script generated by MySQL Workbench
-- Mon Apr 23 16:13:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema shortbox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shortbox` DEFAULT CHARACTER SET utf8 ;
USE `shortbox` ;


-- -----------------------------------------------------
-- Table `shortbox`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`publisher` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastupdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  FULLTEXT INDEX `fulltext` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 58834
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`series` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `startyear` INT(11) NOT NULL,
  `endyear` INT(11) NULL DEFAULT NULL,
  `volume` INT(11) NOT NULL DEFAULT '0',
  `original` INT(1) NOT NULL DEFAULT '0',
  `fk_publisher` INT(11) UNSIGNED NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastupdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title` USING BTREE (`title` ASC, `volume` ASC, `fk_publisher` ASC),
  INDEX `fk_publisher` (`fk_publisher` ASC),
  FULLTEXT INDEX `fulltext` (`title` ASC),
  CONSTRAINT `series_ibfk_1`
    FOREIGN KEY (`fk_publisher`)
    REFERENCES `shortbox`.`publisher` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101672
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`issue` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `fk_series` INT(11) UNSIGNED NOT NULL,
  `number` VARCHAR(255) NOT NULL DEFAULT '',
  `format` VARCHAR(255) NOT NULL DEFAULT '',
  `variant` VARCHAR(255) NOT NULL DEFAULT '',
  `limited` INT(10) UNSIGNED NULL DEFAULT NULL,
  `language` VARCHAR(255) NULL DEFAULT NULL,
  `pages` INT(11) UNSIGNED NULL DEFAULT NULL,
  `releasedate` DATE NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `currency` VARCHAR(3) NULL DEFAULT NULL,
  `coverurl` VARCHAR(255) NULL DEFAULT 'www.shortbox.xyz/res/dummycover.png',
  `dirty` TINYINT(1) NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastupdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number` USING BTREE (`number` ASC, `fk_series` ASC, `format` ASC, `variant` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_series` (`fk_series` ASC),
  CONSTRAINT `fk_series`
    FOREIGN KEY (`fk_series`)
    REFERENCES `shortbox`.`series` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43519
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NOT NULL DEFAULT '',
  `password` VARCHAR(255) NOT NULL DEFAULT '',
  `registered` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastlogin` TIMESTAMP NULL DEFAULT NULL,
  `usergroup` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`list` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `sort` INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `groupby` VARCHAR(255) NOT NULL DEFAULT '',
  `fk_user` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC, `fk_user` ASC),
  INDEX `list_ibfk_1` (`fk_user` ASC),
  CONSTRAINT `list_ibfk_1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `shortbox`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`issue_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`issue_list` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_issue` INT(11) UNSIGNED NOT NULL,
  `fk_list` INT(11) UNSIGNED NOT NULL,
  `amount` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fk_issue` (`fk_issue` ASC, `fk_list` ASC),
  INDEX `fk_list` (`fk_list` ASC),
  CONSTRAINT `issue_list_ibfk_1`
    FOREIGN KEY (`fk_issue`)
    REFERENCES `shortbox`.`issue` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `issue_list_ibfk_2`
    FOREIGN KEY (`fk_list`)
    REFERENCES `shortbox`.`list` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3119
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`story` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `number` INT(11) NULL DEFAULT NULL,
  `additionalinfo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `title` (`title` ASC, `number` ASC, `additionalinfo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 36492
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`issue_story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`issue_story` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_issue` INT(11) UNSIGNED NOT NULL,
  `fk_story` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `issue_story_UNIQUE` (`fk_issue` ASC, `fk_story` ASC),
  INDEX `fk_issue_idx` (`fk_issue` ASC),
  INDEX `fk_story_idx` (`fk_story` ASC),
  CONSTRAINT `issue_story_ibfk_1`
    FOREIGN KEY (`fk_issue`)
    REFERENCES `shortbox`.`issue` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `issue_story_ibfk_2`
    FOREIGN KEY (`fk_story`)
    REFERENCES `shortbox`.`story` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 47625
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`tag` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `calls` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`issue_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`issue_tag` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_issue` INT(10) UNSIGNED NOT NULL,
  `fk_tag` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `issue_tag_UNIQUE` (`fk_issue` ASC, `fk_tag` ASC),
  INDEX `fk_issue_idx` (`fk_issue` ASC),
  INDEX `fk_tag_idx` (`fk_tag` ASC),
  CONSTRAINT `issue_tag_ibfk_1`
    FOREIGN KEY (`fk_issue`)
    REFERENCES `shortbox`.`issue` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `issue_tag_ibfk_2`
    FOREIGN KEY (`fk_tag`)
    REFERENCES `shortbox`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`session` (
  `id` VARCHAR(255) NOT NULL,
  `fk_user` INT(10) UNSIGNED NOT NULL,
  `lastaccess` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `host` VARCHAR(255) NOT NULL DEFAULT '',
  `keep` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `host_UNIQUE` (`host` ASC),
  INDEX `fk_user_idx` (`fk_user` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`fk_user`)
    REFERENCES `shortbox`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shortbox`.`variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortbox`.`variant` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_issue` INT(11) UNSIGNED NOT NULL,
  `fk_variant` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fk_issue` (`fk_issue` ASC, `fk_variant` ASC),
  INDEX `fk_variant` (`fk_variant` ASC),
  CONSTRAINT `variant_ibfk_1`
    FOREIGN KEY (`fk_issue`)
    REFERENCES `shortbox`.`issue` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `variant_ibfk_2`
    FOREIGN KEY (`fk_variant`)
    REFERENCES `shortbox`.`issue` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1043
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
